name:                breaths
version:             0.1.0.0
github:              "kvsari/breaths"
license:             BSD3
author:              "Stephan Luther"
maintainer:          "kvsari@gmail.com"
copyright:           "Copyright (c) 2019 Stephan Luther"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kvsari/breaths#readme>

dependencies:
- base >= 4.7 && < 5
- hscurses

library:
  source-dirs: src

executables:
  breaths-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - breaths

tests:
  breaths-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - breaths
